In [1]:
import numpy as np

In [12]:
lst=[i for i in range(10)]
arr=np.arange(10)

In [2]:
#create array
arr=np.array([])

In [3]:
type(arr)

numpy.ndarray

In [4]:
#1d array
#vector>1D
arr=np.array([1,2,3,4,5])

In [5]:
arr

array([1, 2, 3, 4, 5])

In [18]:
arr[-1]

np.int64(5)

In [17]:
arr[0:2]

array([1, 2])

In [19]:
arr[0:5:2]

array([1, 3, 5])

In [20]:
arr=np.array([ [1,2,3] 
            , [4,5,6] ])

In [21]:
arr.ndim

2

In [ ]:
arr[0,0] 

np.int64(1)

In [23]:
arr[0,:]

array([1, 2, 3])

In [24]:
arr[:,2]

array([3, 6])

In [25]:
arr=np.array([[1,2,3] 
            , [4,5,6]
            , [7,8,9] ])

In [26]:
arr[::2,1]

array([2, 8])

In [27]:
arr[::2 , ::2]

array([[1, 3],
       [7, 9]])

In [28]:
#3D
arr=np.array([   [[1,2,3] 
                , [4,5,6]
                , [7,8,9] ]
             ,
             [[1,2,3] 
            , [4,5,6]
            , [7,8,9] ]  ])

In [29]:
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [30]:
arr.shape

(2, 3, 3)

In [31]:
arr[0,1,1]

np.int64(5)

In [32]:
arr[0,:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
#slicing
arr[0, 0:2 , 1]

array([2, 5])

In [34]:
arr.ndim

3

In [35]:
arr.size

18

In [36]:
arr.dtype

dtype('int64')

In [37]:
type(arr)

numpy.ndarray

In [6]:
arr=np.array([1,2,3,4,5],dtype="float")

In [7]:
arr

array([1., 2., 3., 4., 5.])

In [5]:
arr.astype("float")

array([1., 2., 3., 4., 5.])

In [41]:
arr.ndim

1

In [11]:
ar=np.array([1,2,3,4,5] , ndmin=5)

In [13]:
ar.ndim

5

In [14]:
ar

array([[[[[1, 2, 3, 4, 5]]]]])

In [15]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [16]:
np.ones((2,4,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [49]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [51]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [53]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
np.arange(10,21,2)

array([10, 12, 14, 16, 18, 20])

In [57]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [19]:
import numpy.random as npr

In [20]:
npr.rand(2,2)

array([[0.06776456, 0.18731415],
       [0.12404184, 0.72789426]])

In [21]:
npr.random((2,2))

array([[0.56600558, 0.36223821],
       [0.17182257, 0.56167813]])

In [22]:
npr.randn(2,2)

array([[ 0.28389848,  1.41553913],
       [ 1.66976707, -2.06546309]])

In [63]:
npr.randint(1, 10, (5,5))

array([[6, 8, 1, 5, 5],
       [8, 8, 4, 3, 1],
       [1, 4, 1, 4, 9],
       [3, 8, 5, 4, 6],
       [6, 7, 7, 1, 2]], dtype=int32)

In [ ]:
npr.rand(2,2) 

array([[0.46307042, 0.09589506],
       [0.9194033 , 0.66301419]])

In [65]:
npr.random((2,))

array([0.98065858, 0.16492885])

In [66]:
npr.randn(2,2)

array([[ 0.21280774, -0.1563106 ],
       [-1.40162595, -1.06725271]])

In [23]:
a=np.array([1,2,3,4])
b=np.array([8,7,1,4])

In [68]:
a+b

array([9, 9, 4, 8])

In [69]:
np.add(a,b)

array([9, 9, 4, 8])

In [70]:
a-b

array([-7, -5,  2,  0])

In [71]:
a*b

array([ 8, 14,  3, 16])

In [24]:
np.dot(a,b)

np.int64(41)

In [25]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [26]:
np.log1p(a)

array([0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [27]:
a>b

array([False, False,  True, False])

In [31]:
a=np.array([   [1,2,3]
            ,[4,5,6] ])

In [32]:
np.sum(a,axis=1)

array([ 6, 15])

In [33]:
np.sum(a,axis=0)

array([5, 7, 9])

In [29]:
np.max(a)

np.int64(4)

In [72]:
a=np.array([1,2,3,4])

In [73]:
a

array([1, 2, 3, 4])

In [74]:
np.append(a,[10,20])

array([ 1,  2,  3,  4, 10, 20])

In [75]:
a

array([1, 2, 3, 4])

In [77]:
np.insert(a,2,200)

array([  1,   2, 200,   3,   4])

In [78]:
np.delete(a,[2])

array([1, 2, 4])

In [79]:
a

array([1, 2, 3, 4])

In [81]:
a=np.array([ [1,2,3] 
            , [4,5,6] ])

In [82]:
a.shape

(2, 3)

In [34]:
a=npr.randint(1,10,(2,6))

In [35]:
a

array([[4, 3, 7, 5, 2, 9],
       [6, 5, 2, 5, 4, 3]], dtype=int32)

In [84]:
a.shape

(2, 6)

In [85]:
a.size

12

In [88]:
a.reshape(2,2,3)

array([[[6, 6, 5],
        [6, 7, 9]],

       [[6, 1, 5],
        [6, 8, 7]]], dtype=int32)

In [89]:
#flatten nd > 1d
a.flatten()

array([6, 6, 5, 6, 7, 9, 6, 1, 5, 6, 8, 7], dtype=int32)

In [ ]:
a.reshape(-1) 

array([6, 6, 5, 6, 7, 9, 6, 1, 5, 6, 8, 7], dtype=int32)

In [91]:
#condition arr
a=np.arange(20)

In [92]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [93]:
a[a>14]

array([15, 16, 17, 18, 19])

In [95]:
np.where(a>14)

(array([15, 16, 17, 18, 19]),)

In [96]:
np.where(a>10 , 10 , a)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10])

In [37]:
a=npr.randint(1, 10,5)

In [39]:
b=npr.randint(1, 10,5)

In [38]:
a

array([8, 5, 3, 7, 9], dtype=int32)

In [40]:
b

array([2, 4, 5, 4, 1], dtype=int32)

In [42]:
np.vstack((a,b))

array([[8, 5, 3, 7, 9],
       [2, 4, 5, 4, 1]], dtype=int32)

In [44]:
np.hstack((a,b))

array([8, 5, 3, 7, 9, 2, 4, 5, 4, 1], dtype=int32)

In [45]:
np.concatenate((a,b))

array([8, 5, 3, 7, 9, 2, 4, 5, 4, 1], dtype=int32)

In [54]:
a=npr.randint(1, 10,(2,4))

In [55]:
a

array([[2, 4, 5, 1],
       [6, 2, 1, 1]], dtype=int32)

In [56]:
np.vsplit(a, 2)

[array([[2, 4, 5, 1]], dtype=int32), array([[6, 2, 1, 1]], dtype=int32)]

In [57]:
np.hsplit(a, 2)

[array([[2, 4],
        [6, 2]], dtype=int32),
 array([[5, 1],
        [1, 1]], dtype=int32)]

In [ ]:
np.save

In [114]:
a

array([3, 4, 3, 2, 2, 2, 9, 8, 8, 7], dtype=int32)

In [115]:
np.append(a,[10,11])

array([ 3,  4,  3,  2,  2,  2,  9,  8,  8,  7, 10, 11])

In [105]:
np.insert(a,3,30)

array([ 0,  1,  2, 30,  3,  4,  5,  6,  7,  8,  9])

In [116]:
a=a.astype("str")

In [117]:
a[0]="hello"

In [118]:
a

array(['hello', '4', '3', '2', '2', '2', '9', '8', '8', '7'], dtype='<U11')

In [ ]:
np.delete(a,[2])

array(['hello', '4', '2', '2', '2', '9', '8', '8', '7'], dtype='<U11')

: 